package com.rana.book.domain;
// Generated Aug 1, 2018 1:12:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BookList generated by hbm2java
 */

@Entity
@Table(name="book_list"
    ,catalog="book_store"
)
public class BookList  implements java.io.Serializable {


     private Integer bookId;
     private Author author;
     private Category category;
     private Publisher publisher;
     private SubCategory subCategory;
     private String bookTitle;
     private String bookPrice;
     private String bookDiscount;
     private String bookUrl;
     private String bookStatus;
     private Set<Image> images = new HashSet<Image>(0);
     private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);
     private Set<Order> orders = new HashSet<Order>(0);

    public BookList() {
    }

	
    public BookList(Author author, Category category, Publisher publisher, SubCategory subCategory, String bookTitle, String bookPrice, String bookDiscount, String bookUrl, String bookStatus) {
        this.author = author;
        this.category = category;
        this.publisher = publisher;
        this.subCategory = subCategory;
        this.bookTitle = bookTitle;
        this.bookPrice = bookPrice;
        this.bookDiscount = bookDiscount;
        this.bookUrl = bookUrl;
        this.bookStatus = bookStatus;
    }
    public BookList(Author author, Category category, Publisher publisher, SubCategory subCategory, String bookTitle, String bookPrice, String bookDiscount, String bookUrl, String bookStatus, Set<Image> images, Set<OrderDetails> orderDetailses, Set<Order> orders) {
       this.author = author;
       this.category = category;
       this.publisher = publisher;
       this.subCategory = subCategory;
       this.bookTitle = bookTitle;
       this.bookPrice = bookPrice;
       this.bookDiscount = bookDiscount;
       this.bookUrl = bookUrl;
       this.bookStatus = bookStatus;
       this.images = images;
       this.orderDetailses = orderDetailses;
       this.orders = orders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="book_id", unique=true, nullable=false)
    public Integer getBookId() {
        return this.bookId;
    }
    
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="auth_id", nullable=false)
    public Author getAuthor() {
        return this.author;
    }
    
    public void setAuthor(Author author) {
        this.author = author;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cat_id", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pub_id", nullable=false)
    public Publisher getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(Publisher publisher) {
        this.publisher = publisher;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sub_cat_id", nullable=false)
    public SubCategory getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(SubCategory subCategory) {
        this.subCategory = subCategory;
    }

    
    @Column(name="book_title", nullable=false, length=45)
    public String getBookTitle() {
        return this.bookTitle;
    }
    
    public void setBookTitle(String bookTitle) {
        this.bookTitle = bookTitle;
    }

    
    @Column(name="book_price", nullable=false, length=45)
    public String getBookPrice() {
        return this.bookPrice;
    }
    
    public void setBookPrice(String bookPrice) {
        this.bookPrice = bookPrice;
    }

    
    @Column(name="book_discount", nullable=false, length=45)
    public String getBookDiscount() {
        return this.bookDiscount;
    }
    
    public void setBookDiscount(String bookDiscount) {
        this.bookDiscount = bookDiscount;
    }

    
    @Column(name="book_url", nullable=false, length=45)
    public String getBookUrl() {
        return this.bookUrl;
    }
    
    public void setBookUrl(String bookUrl) {
        this.bookUrl = bookUrl;
    }

    
    @Column(name="book_status", nullable=false, length=45)
    public String getBookStatus() {
        return this.bookStatus;
    }
    
    public void setBookStatus(String bookStatus) {
        this.bookStatus = bookStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bookList")
    public Set<Image> getImages() {
        return this.images;
    }
    
    public void setImages(Set<Image> images) {
        this.images = images;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bookList")
    public Set<OrderDetails> getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
        this.orderDetailses = orderDetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bookList")
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


