package com.rana.book.domain;
// Generated Aug 1, 2018 1:12:53 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="order"
    ,catalog="book_store"
)
public class Order  implements java.io.Serializable {


     private Integer orderId;
     private BookList bookList;
     private User user;
     private int orderQty;
     private Date orderDate;
     private String orderStatus;
     private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

    public Order() {
    }

	
    public Order(BookList bookList, User user, int orderQty, Date orderDate, String orderStatus) {
        this.bookList = bookList;
        this.user = user;
        this.orderQty = orderQty;
        this.orderDate = orderDate;
        this.orderStatus = orderStatus;
    }
    public Order(BookList bookList, User user, int orderQty, Date orderDate, String orderStatus, Set<OrderDetails> orderDetailses) {
       this.bookList = bookList;
       this.user = user;
       this.orderQty = orderQty;
       this.orderDate = orderDate;
       this.orderStatus = orderStatus;
       this.orderDetailses = orderDetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="order_id", unique=true, nullable=false)
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="book_id", nullable=false)
    public BookList getBookList() {
        return this.bookList;
    }
    
    public void setBookList(BookList bookList) {
        this.bookList = bookList;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="order_qty", nullable=false)
    public int getOrderQty() {
        return this.orderQty;
    }
    
    public void setOrderQty(int orderQty) {
        this.orderQty = orderQty;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="order_date", nullable=false, length=10)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    
    @Column(name="order_status", nullable=false, length=45)
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="order")
    public Set<OrderDetails> getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
        this.orderDetailses = orderDetailses;
    }




}


