package com.rana.book.domain;
// Generated Aug 1, 2018 1:12:53 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name="order_details"
    ,catalog="book_store"
)
public class OrderDetails  implements java.io.Serializable {


     private Integer orderDetailId;
     private BookList bookList;
     private Order order;
     private double bookTotalPrice;
     private double bookPrice;
     private double bookDiscount;
     private double bookNetPrice;

    public OrderDetails() {
    }

    public OrderDetails(BookList bookList, Order order, double bookTotalPrice, double bookPrice, double bookDiscount, double bookNetPrice) {
       this.bookList = bookList;
       this.order = order;
       this.bookTotalPrice = bookTotalPrice;
       this.bookPrice = bookPrice;
       this.bookDiscount = bookDiscount;
       this.bookNetPrice = bookNetPrice;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="order_detail_id", unique=true, nullable=false)
    public Integer getOrderDetailId() {
        return this.orderDetailId;
    }
    
    public void setOrderDetailId(Integer orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="book_id", nullable=false)
    public BookList getBookList() {
        return this.bookList;
    }
    
    public void setBookList(BookList bookList) {
        this.bookList = bookList;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false)
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }

    
    @Column(name="book_total_price", nullable=false, precision=22, scale=0)
    public double getBookTotalPrice() {
        return this.bookTotalPrice;
    }
    
    public void setBookTotalPrice(double bookTotalPrice) {
        this.bookTotalPrice = bookTotalPrice;
    }

    
    @Column(name="book_price", nullable=false, precision=22, scale=0)
    public double getBookPrice() {
        return this.bookPrice;
    }
    
    public void setBookPrice(double bookPrice) {
        this.bookPrice = bookPrice;
    }

    
    @Column(name="book_discount", nullable=false, precision=22, scale=0)
    public double getBookDiscount() {
        return this.bookDiscount;
    }
    
    public void setBookDiscount(double bookDiscount) {
        this.bookDiscount = bookDiscount;
    }

    
    @Column(name="book_net_price", nullable=false, precision=22, scale=0)
    public double getBookNetPrice() {
        return this.bookNetPrice;
    }
    
    public void setBookNetPrice(double bookNetPrice) {
        this.bookNetPrice = bookNetPrice;
    }




}


