package com.rana.book.domain;
// Generated Aug 1, 2018 1:12:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Publisher generated by hbm2java
 */
@Entity
@Table(name="publisher"
    ,catalog="book_store"
)
public class Publisher  implements java.io.Serializable {


     private Integer pubId;
     private String pubName;
     private String pubAddress;
     private String pubContact;
     private String pubCountry;
     private Set<BookList> bookLists = new HashSet<BookList>(0);

    public Publisher() {
    }

	
    public Publisher(String pubName, String pubAddress, String pubContact, String pubCountry) {
        this.pubName = pubName;
        this.pubAddress = pubAddress;
        this.pubContact = pubContact;
        this.pubCountry = pubCountry;
    }
    public Publisher(String pubName, String pubAddress, String pubContact, String pubCountry, Set<BookList> bookLists) {
       this.pubName = pubName;
       this.pubAddress = pubAddress;
       this.pubContact = pubContact;
       this.pubCountry = pubCountry;
       this.bookLists = bookLists;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pub_id", unique=true, nullable=false)
    public Integer getPubId() {
        return this.pubId;
    }
    
    public void setPubId(Integer pubId) {
        this.pubId = pubId;
    }

    
    @Column(name="pub_name", nullable=false, length=45)
    public String getPubName() {
        return this.pubName;
    }
    
    public void setPubName(String pubName) {
        this.pubName = pubName;
    }

    
    @Column(name="pub_address", nullable=false, length=45)
    public String getPubAddress() {
        return this.pubAddress;
    }
    
    public void setPubAddress(String pubAddress) {
        this.pubAddress = pubAddress;
    }

    
    @Column(name="pub_contact", nullable=false, length=45)
    public String getPubContact() {
        return this.pubContact;
    }
    
    public void setPubContact(String pubContact) {
        this.pubContact = pubContact;
    }

    
    @Column(name="pub_country", nullable=false, length=45)
    public String getPubCountry() {
        return this.pubCountry;
    }
    
    public void setPubCountry(String pubCountry) {
        this.pubCountry = pubCountry;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="publisher")
    public Set<BookList> getBookLists() {
        return this.bookLists;
    }
    
    public void setBookLists(Set<BookList> bookLists) {
        this.bookLists = bookLists;
    }




}


