package com.rana.book.domain;
// Generated Aug 1, 2018 1:12:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SubCategory generated by hbm2java
 */
@Entity
@Table(name="sub_category"
    ,catalog="book_store"
)
public class SubCategory  implements java.io.Serializable {


     private Integer subCatId;
     private Category category;
     private String subCatName;
     private String subCatDesc;
     private Set<BookList> bookLists = new HashSet<BookList>(0);

    public SubCategory() {
    }

	
    public SubCategory(Category category, String subCatName, String subCatDesc) {
        this.category = category;
        this.subCatName = subCatName;
        this.subCatDesc = subCatDesc;
    }
    public SubCategory(Category category, String subCatName, String subCatDesc, Set<BookList> bookLists) {
       this.category = category;
       this.subCatName = subCatName;
       this.subCatDesc = subCatDesc;
       this.bookLists = bookLists;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sub_cat_id", unique=true, nullable=false)
    public Integer getSubCatId() {
        return this.subCatId;
    }
    
    public void setSubCatId(Integer subCatId) {
        this.subCatId = subCatId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cat_id", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="sub_cat_name", nullable=false, length=45)
    public String getSubCatName() {
        return this.subCatName;
    }
    
    public void setSubCatName(String subCatName) {
        this.subCatName = subCatName;
    }

    
    @Column(name="sub_cat_desc", nullable=false, length=45)
    public String getSubCatDesc() {
        return this.subCatDesc;
    }
    
    public void setSubCatDesc(String subCatDesc) {
        this.subCatDesc = subCatDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subCategory")
    public Set<BookList> getBookLists() {
        return this.bookLists;
    }
    
    public void setBookLists(Set<BookList> bookLists) {
        this.bookLists = bookLists;
    }




}


