package com.rana.book.domain;
// Generated Aug 1, 2018 1:12:53 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UpcomingBook generated by hbm2java
 */
@Entity
@Table(name="upcoming_book"
    ,catalog="book_store"
)
public class UpcomingBook  implements java.io.Serializable {


     private Integer bookId;
     private String authName;
     private Date PDate;

    public UpcomingBook() {
    }

    public UpcomingBook(String authName, Date PDate) {
       this.authName = authName;
       this.PDate = PDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="book_id", unique=true, nullable=false)
    public Integer getBookId() {
        return this.bookId;
    }
    
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    
    @Column(name="auth_name", nullable=false, length=45)
    public String getAuthName() {
        return this.authName;
    }
    
    public void setAuthName(String authName) {
        this.authName = authName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="p_date", nullable=false, length=10)
    public Date getPDate() {
        return this.PDate;
    }
    
    public void setPDate(Date PDate) {
        this.PDate = PDate;
    }




}


